### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by Dextrode** [Dextrode/Portfolio#1]
**Browser Testing**
- [ ] Opera
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Brave

**Devices**
- [ ] Mobile device (iOS)
- [ ] Tablet (Android) (641 x 1007)
- [ ] Laptop size (1366 x 768)
- [ ] Desktop (1920 x 1080)

**Code & Optimization**
- [ ] All Images under 650kb
- [ ] All Thumbnail Images under 200kb
- [ ] Inspector Console is free of errors
- [ ] No PHP warnings
- [ ] Favicon included and linked correctly 
- [ ] Page Speed (Mobile) 45+
- [ ] Page Speed (Desktop) 70+
- [ ] All code run through W3C Checker and error free
- [ ] Domain name set up and DNS pointed correctly to web server
- [ ] SSL certificate installed 
- [ ] HTML, CSS and JS files minified and concatenated where possible
- [ ] Bootstrap Modules removed

**Content**
- [ ] Text checked and free from spelling, grammatical, factual and formatting errors
- [ ] Page titles and meta data (e.g. meta description and open graph tags) present, unique and descriptive
- [ ] Images have appropriate alt attribute
- [ ] Schema markup included
- [ ] Navigation easy to find and use, and all links working
- [ ] 404 page created and serving correctly 
- [ ] Footer copyright notice included, year(s) correct and creative commons license included if desired
- [ ] Code linked for all artifacts
- [ ] External links across web pages are working properly, and open in a new tab.

**Communication**
- [ ] Contact details correct and easy to find 
- [ ] Links to social media accounts present and correct
- [ ] Analytics tracking installed and working 
- [ ] Contact details correct and easy to find
