### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Dextrode** [Dextrode/Portfolio#4]
# Launch Checklist

## Browser Testing
- [x] Opera
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Brave

## Devices
- [x] #12
- [x] Tablet (Android) (641 x 1007)
- [x] Laptop size (1366 x 768)
- [x] Desktop (1920 x 1080)

## Code & Optimization
- [x] #7 
- [x] #6
- [x] Inspector Console is free of errors
- [x] No PHP warnings
- [x] Favicon included and linked correctly 
- [x] Lighthouse 85+ Performance
- [x] Lighthouse 95+ Accessibility 
- [x] All code run through W3C Checker and error free
- [x] Domain name set up and DNS pointed correctly to web server
- [x] SSL certificate installed 
- [x] #13
- [x] #11
- [x] #9

## Content
- [x] Text checked and free from spelling, grammatical, factual and formatting errors
- [x] Page titles and meta data (e.g. meta description and open graph tags) present, unique and descriptive
- [x] Images have appropriate alt attribute
- [x] Schema markup included
- [x] Navigation easy to find and use, and all links working
- [x] #5
- [x] #8 
- [x] Code linked for all artifacts
- [x] External links across web pages are working properly, and open in a new tab.

## Communication
- [x] #10
- [x] Links to social media accounts present and correct
- [x] Analytic tracking installed and working
